---
title: "slurm-script-generator"
engine: knitr
execute:
  echo: true
  output: true
---

Check out the [documentation](https://max-models.github.io/slurm-script-generator) for more details and examples!

## Installation

```bash
pip install slurm-script-generator
```
## Generate scripts

Generate a slurm script to `slurm_script.sh` with

```{bash}
generate-slurm-script --nodes 1 --ntasks-per-node 16
```

To save the script to file `my_script.sh` use `--output-path`:

```{bash}
generate-slurm-script --nodes 1 --ntasks-per-node 16 --output-path my_script.sh
```

Remove the header comment with `--no-header`:

```{bash}
generate-slurm-script --nodes 1 --ntasks-per-node 16 --no-header
```

You can also generate scripts in Python programmatically:

```{python}
from slurm_script_generator.slurm_script import SlurmScript

slurm_script = SlurmScript(
    nodes=2,
    ntasks_per_core=16,
    custom_commands=[
        "# Run simulation",
        "srun ./bin > run.out",
    ],
)

print(slurm_script)
```

You can also generate a string representation of the script with `generate_script`:

```{python}
script = slurm_script.generate_script()
```

You can read more examples of the Python API in the [tutorial notebooks](https://max-models.github.io/slurm-script-generator/tutorials.html).

## Exporting and reading scripts

To export the settings to a json file you can use `--export-json`:

```{bash}
generate-slurm-script --nodes 2 --export-json setup.json --no-header
```

This json file can used as a basis for creating new scripts

```{bash}
generate-slurm-script --input setup.json --ntasks-per-node 16 --no-header
```

### Add modules

Add modules with

```{bash}
generate-slurm-script --input setup.json --ntasks-per-node 16 --modules gcc/13 openmpi/5.0 --no-header
```

### Read from script

You can also read pragmas and commands from an existing script with `--read-script`:

Let's say you have a script `slurm_script.sh` with the following content:

```{bash}
cat slurm_script.sh
```

You can read the script and add extra pragmas (for example, changing the job name with `--job-name NEW_JOB_NAME`) or commands to generate a new script with

```{bash}
generate-slurm-script --read-script slurm_script.sh --job-name NEW_JOB_NAME --no-header
```

### Other

All optional arguments can be shown with

```{bash}
generate-slurm-script -h
```
